name: Generate GitBlog README

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - main
    paths:
      - main.py

env:
  GITHUB_NAME: GeorgeCh2
  GITHUB_EMAIL: georgechmr@gmail.com

jobs:
  sync:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Generate new md
        run: |
          source venv/bin/activate
          python main.py ${{ secrets.G_T }} ${{ github.repository }} --issue_numbe '${{ github.event.issue.number }}'
        
      - name: Push README
        run: |
          git config --local user.name georgechou
          git config --local user.email georgechmr@gmail.com
          git add .
          git commit -m "generated readme" || echo "no need to commit "
          git push || echo "no file change"
